In [1]:
stats = [
    'goals',
    'score_halftime',
    'score_secondtime',
#     'shots_on_goal',
#     'shots_off_goal',
#     'total_shots',
#     'blocked_shots',
#     'shots_inside_box',
#     'shots_outside_box',
#     'fouls',
    'corner_kicks',
#     'offsides',
#     'ball_possession',
    'yellow_cards',
#     'red_cards',
#     'goalkeeper_saves',
#     'total_passess',
#     'passess_accurate',
#     'passess', 
    'cards'
]

In [2]:
end_col = 'red_cards_away'

In [3]:
import mysql.connector

# ALTER TABLE `football_fixtures` ADD `aaa` DECIMAL(5,3) NULL DEFAULT NULL AFTER `end_exact_score`; 

# -----------------------------------------------------------------
# -----------------------------------------------------------------
for x in stats:
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_for_home'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query) 
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_for_home_ratio'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query) 
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_against_home'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query) 
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_against_home_ratio'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query)  
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    
    
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_for_away'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query) 
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_for_away_ratio'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query) 
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_against_away'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query) 
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    # -------------------------------------------------------------
    host="localhost"
    user="root"
    database="pr_mmbuzz_2022_06" 
    mydb = mysql.connector.connect( host=host, user=user, password="", database=database )
    mycursor = mydb.cursor()
    # -------------------------------------------------------------
    new_col = x + '_against_away_ratio'
    query = "ALTER TABLE `football_odds` ADD `"+new_col+"` DOUBLE NULL DEFAULT NULL AFTER `"+end_col+"`;"
    end_col = new_col
    print(query) 
    print("")
    # -----------------------------------------------------------------
    mycursor.execute(query)
    mydb.commit()  
    # ------------------------ close the cursor and database connection
    mycursor.close()
    mydb.close()  
# -----------------------------------------------------------------

ALTER TABLE `football_odds` ADD `goals_for_home` DOUBLE NULL DEFAULT NULL AFTER `red_cards_away`;

ALTER TABLE `football_odds` ADD `goals_for_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `goals_for_home`;

ALTER TABLE `football_odds` ADD `goals_against_home` DOUBLE NULL DEFAULT NULL AFTER `goals_for_home_ratio`;

ALTER TABLE `football_odds` ADD `goals_against_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `goals_against_home`;

ALTER TABLE `football_odds` ADD `goals_for_away` DOUBLE NULL DEFAULT NULL AFTER `goals_against_home_ratio`;

ALTER TABLE `football_odds` ADD `goals_for_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `goals_for_away`;

ALTER TABLE `football_odds` ADD `goals_against_away` DOUBLE NULL DEFAULT NULL AFTER `goals_for_away_ratio`;

ALTER TABLE `football_odds` ADD `goals_against_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `goals_against_away`;

ALTER TABLE `football_odds` ADD `score_halftime_for_home` DOUBLE NULL DEFAULT NULL AFTER `goals_against_away_ratio`;

ALTER TABLE `football_odds` ADD `score_halftime_for_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_for_home`;

ALTER TABLE `football_odds` ADD `score_halftime_against_home` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_for_home_ratio`;

ALTER TABLE `football_odds` ADD `score_halftime_against_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_against_home`;

ALTER TABLE `football_odds` ADD `score_halftime_for_away` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_against_home_ratio`;

ALTER TABLE `football_odds` ADD `score_halftime_for_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_for_away`;

ALTER TABLE `football_odds` ADD `score_halftime_against_away` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_for_away_ratio`;

ALTER TABLE `football_odds` ADD `score_halftime_against_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_against_away`;

ALTER TABLE `football_odds` ADD `score_secondtime_for_home` DOUBLE NULL DEFAULT NULL AFTER `score_halftime_against_away_ratio`;

ALTER TABLE `football_odds` ADD `score_secondtime_for_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_for_home`;

ALTER TABLE `football_odds` ADD `score_secondtime_against_home` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_for_home_ratio`;

ALTER TABLE `football_odds` ADD `score_secondtime_against_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_against_home`;

ALTER TABLE `football_odds` ADD `score_secondtime_for_away` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_against_home_ratio`;

ALTER TABLE `football_odds` ADD `score_secondtime_for_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_for_away`;

ALTER TABLE `football_odds` ADD `score_secondtime_against_away` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_for_away_ratio`;

ALTER TABLE `football_odds` ADD `score_secondtime_against_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_against_away`;

ALTER TABLE `football_odds` ADD `corner_kicks_for_home` DOUBLE NULL DEFAULT NULL AFTER `score_secondtime_against_away_ratio`;

ALTER TABLE `football_odds` ADD `corner_kicks_for_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_for_home`;

ALTER TABLE `football_odds` ADD `corner_kicks_against_home` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_for_home_ratio`;

ALTER TABLE `football_odds` ADD `corner_kicks_against_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_against_home`;

ALTER TABLE `football_odds` ADD `corner_kicks_for_away` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_against_home_ratio`;

ALTER TABLE `football_odds` ADD `corner_kicks_for_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_for_away`;

ALTER TABLE `football_odds` ADD `corner_kicks_against_away` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_for_away_ratio`;

ALTER TABLE `football_odds` ADD `corner_kicks_against_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_against_away`;

ALTER TABLE `football_odds` ADD `yellow_cards_for_home` DOUBLE NULL DEFAULT NULL AFTER `corner_kicks_against_away_ratio`;

ALTER TABLE `football_odds` ADD `yellow_cards_for_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_for_home`;

ALTER TABLE `football_odds` ADD `yellow_cards_against_home` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_for_home_ratio`;

ALTER TABLE `football_odds` ADD `yellow_cards_against_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_against_home`;

ALTER TABLE `football_odds` ADD `yellow_cards_for_away` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_against_home_ratio`;

ALTER TABLE `football_odds` ADD `yellow_cards_for_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_for_away`;

ALTER TABLE `football_odds` ADD `yellow_cards_against_away` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_for_away_ratio`;

ALTER TABLE `football_odds` ADD `yellow_cards_against_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_against_away`;

ALTER TABLE `football_odds` ADD `cards_for_home` DOUBLE NULL DEFAULT NULL AFTER `yellow_cards_against_away_ratio`;

ALTER TABLE `football_odds` ADD `cards_for_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `cards_for_home`;

ALTER TABLE `football_odds` ADD `cards_against_home` DOUBLE NULL DEFAULT NULL AFTER `cards_for_home_ratio`;

ALTER TABLE `football_odds` ADD `cards_against_home_ratio` DOUBLE NULL DEFAULT NULL AFTER `cards_against_home`;

ALTER TABLE `football_odds` ADD `cards_for_away` DOUBLE NULL DEFAULT NULL AFTER `cards_against_home_ratio`;

ALTER TABLE `football_odds` ADD `cards_for_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `cards_for_away`;

ALTER TABLE `football_odds` ADD `cards_against_away` DOUBLE NULL DEFAULT NULL AFTER `cards_for_away_ratio`;

ALTER TABLE `football_odds` ADD `cards_against_away_ratio` DOUBLE NULL DEFAULT NULL AFTER `cards_against_away`;