In [4]:
# ------------------------------------------------------
import mysql.connector 
# ------------------------------------------------------
old_col = "passess_away"
# ------------------------------------------------------
host="localhost"
user="root" 
database="pr_mmbuzz_2022_06"
mydb = mysql.connector.connect(host=host,user=user,password="",database=database)
mycursor = mydb.cursor()
# ------------------------------------------------------
query = "select "
query += " bet_id "
query += " , bet  "
query += " , value  "
query += " , columny  "
query += " , columnx  "
query += " from bets_old " 
query += " order by bet_id, total asc " 
# ------------------------------------------------------   
print(query)
# ------------------------------------------------------   
mycursor = mydb.cursor()
mycursor.execute(query)
result =  mycursor.fetchall()
# ------------------------------------------------------ 
for x in result: 
    # -------------------------------------------------- 
    bet_id = str(x[0])
    bet = str(x[1])
    value = str(x[2])
    columny = str(x[3])
    columnx = str(x[4]) 
    # --------------------------------------------------   
    # ALTER TABLE `bets_new` ADD `"+old_col+"` BOOLEAN NULL DEFAULT NULL AFTER `test`; 
    alter =  "ALTER TABLE `football_statistics` ADD `"+columnx+"` BOOLEAN NULL DEFAULT NULL AFTER `"+old_col+"`;"
    old_col = columnx
    print(alter, flush=True) 
    mycursor.execute(alter)
    mydb.commit()  
    # --------------------------------------------------  
# ------------------------------------------------------

select  bet_id  , bet   , value   , columny   , columnx   from bets_old  order by bet_id, total asc
ALTER TABLE `football_statistics` ADD `match_winner_home` BOOLEAN NULL DEFAULT NULL AFTER `passess_away`;
ALTER TABLE `football_statistics` ADD `match_winner_draw` BOOLEAN NULL DEFAULT NULL AFTER `match_winner_home`;
ALTER TABLE `football_statistics` ADD `match_winner_away` BOOLEAN NULL DEFAULT NULL AFTER `match_winner_draw`;
ALTER TABLE `football_statistics` ADD `homeaway_home` BOOLEAN NULL DEFAULT NULL AFTER `match_winner_away`;
ALTER TABLE `football_statistics` ADD `homeaway_away` BOOLEAN NULL DEFAULT NULL AFTER `homeaway_home`;
ALTER TABLE `football_statistics` ADD `second_half_winner_home` BOOLEAN NULL DEFAULT NULL AFTER `homeaway_away`;
ALTER TABLE `football_statistics` ADD `second_half_winner_draw` BOOLEAN NULL DEFAULT NULL AFTER `second_half_winner_home`;
ALTER TABLE `football_statistics` ADD `second_half_winner_away` BOOLEAN NULL DEFAULT NULL AFTER `second_half_winner_draw`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_675` BOOLEAN NULL DEFAULT NULL AFTER `second_half_winner_away`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_675` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_675`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_65` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_675`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_65` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_65`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_625` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_65`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_625` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_625`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_6` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_625`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_6` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_6`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_575` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_6`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_575` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_575`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_55` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_575`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_55` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_55`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_525` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_55`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_525` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_525`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_5` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_525`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_5` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_5`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_475` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_5`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_475` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_475`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_45` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_475`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_45` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_45`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_425` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_45`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_425` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_425`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_4` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_425`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_4` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_4`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_375` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_4`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_375` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_375`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_35` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_375`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_35` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_35`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_325` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_35`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_325` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_325`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_3` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_325`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_3` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_3`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_275` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_3`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_275` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_275`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_25` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_275`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_25` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_25`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_225` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_25`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_225` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_225`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_2` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_225`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_2` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_2`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_175` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_2`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_175` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_175`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_175`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_min_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_min_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_min_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_min_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_0`;

ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_0`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_175` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_175` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_175`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_2` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_175`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_2` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_2`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_225` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_2`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_225` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_225`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_25` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_225`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_25` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_25`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_275` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_25`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_275` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_275`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_3` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_275`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_3` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_3`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_325` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_3`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_325` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_325`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_35` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_325`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_35` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_35`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_375` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_35`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_375` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_375`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_4` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_375`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_4` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_4`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_425` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_4`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_425` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_425`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_45` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_425`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_45` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_45`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_475` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_45`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_475` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_475`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_5` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_475`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_5` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_5`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_525` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_5`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_525` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_525`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_55` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_525`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_55` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_55`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_575` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_55`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_575` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_575`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_6` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_575`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_6` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_6`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_625` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_6`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_625` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_625`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_65` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_625`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_65` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_65`;
ALTER TABLE `football_statistics` ADD `asian_handicap_home_plus_675` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_65`;
ALTER TABLE `football_statistics` ADD `asian_handicap_away_plus_675` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_home_plus_675`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_away_plus_675`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_05` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_05`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_075` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_05`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_075` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_075`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_10` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_075`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_10` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_10`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_125` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_10`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_125` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_125`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_15` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_125`;

ALTER TABLE `football_statistics` ADD `goals_overunder_under_15` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_15`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_175` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_15`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_175` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_175`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_20` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_175`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_20` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_20`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_225` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_20`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_225` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_225`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_25` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_225`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_25` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_275` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_275` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_275`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_30` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_275`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_30` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_30`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_325` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_30`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_325` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_325`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_35` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_325`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_35` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_35`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_375` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_35`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_375` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_375`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_40` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_375`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_40` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_40`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_425` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_40`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_425` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_425`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_45` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_425`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_45` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_45`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_475` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_45`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_475` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_475`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_50` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_475`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_50` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_50`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_525` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_50`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_525` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_525`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_55` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_525`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_55` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_55`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_575` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_55`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_575` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_575`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_60` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_575`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_60` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_60`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_625` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_60`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_625` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_625`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_65` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_625`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_65` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_65`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_675` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_65`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_675` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_675`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_70` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_675`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_70` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_70`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_75` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_70`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_75` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_75`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_85` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_75`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_85` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_85`;
ALTER TABLE `football_statistics` ADD `goals_overunder_over_95` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_85`;
ALTER TABLE `football_statistics` ADD `goals_overunder_under_95` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_over_95`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_05` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_under_95`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_05` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_05`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_075` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_05`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_075` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_075`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_10` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_075`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_10` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_10`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_125` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_10`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_125` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_125`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_15` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_125`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_15` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_15`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_175` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_15`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_175` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_175`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_20` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_175`;

ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_20` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_20`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_225` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_20`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_225` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_225`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_25` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_225`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_25` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_275` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_275` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_275`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_30` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_275`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_30` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_30`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_325` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_30`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_325` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_325`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_35` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_325`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_35` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_35`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_over_375` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_35`;
ALTER TABLE `football_statistics` ADD `goals_overunder_first_half_under_375` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_over_375`;
ALTER TABLE `football_statistics` ADD `htft_double_home_home` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder_first_half_under_375`;
ALTER TABLE `football_statistics` ADD `htft_double_home_draw` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_home_home`;
ALTER TABLE `football_statistics` ADD `htft_double_home_away` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_home_draw`;
ALTER TABLE `football_statistics` ADD `htft_double_draw_home` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_home_away`;
ALTER TABLE `football_statistics` ADD `htft_double_draw_draw` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_draw_home`;
ALTER TABLE `football_statistics` ADD `htft_double_draw_away` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_draw_draw`;
ALTER TABLE `football_statistics` ADD `htft_double_away_home` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_draw_away`;
ALTER TABLE `football_statistics` ADD `htft_double_away_draw` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_away_home`;
ALTER TABLE `football_statistics` ADD `htft_double_away_away` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_away_draw`;
ALTER TABLE `football_statistics` ADD `both_teams_score_yes` BOOLEAN NULL DEFAULT NULL AFTER `htft_double_away_away`;
ALTER TABLE `football_statistics` ADD `both_teams_score_no` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_score_yes`;
ALTER TABLE `football_statistics` ADD `highest_scoring_half_first` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_score_no`;
ALTER TABLE `football_statistics` ADD `highest_scoring_half_draw` BOOLEAN NULL DEFAULT NULL AFTER `highest_scoring_half_first`;
ALTER TABLE `football_statistics` ADD `highest_scoring_half_second` BOOLEAN NULL DEFAULT NULL AFTER `highest_scoring_half_draw`;
ALTER TABLE `football_statistics` ADD `double_chance_home_draw` BOOLEAN NULL DEFAULT NULL AFTER `highest_scoring_half_second`;
ALTER TABLE `football_statistics` ADD `double_chance_home_away` BOOLEAN NULL DEFAULT NULL AFTER `double_chance_home_draw`;
ALTER TABLE `football_statistics` ADD `double_chance_draw_away` BOOLEAN NULL DEFAULT NULL AFTER `double_chance_home_away`;
ALTER TABLE `football_statistics` ADD `first_half_winner_home` BOOLEAN NULL DEFAULT NULL AFTER `double_chance_draw_away`;
ALTER TABLE `football_statistics` ADD `first_half_winner_draw` BOOLEAN NULL DEFAULT NULL AFTER `first_half_winner_home`;
ALTER TABLE `football_statistics` ADD `first_half_winner_away` BOOLEAN NULL DEFAULT NULL AFTER `first_half_winner_draw`;
ALTER TABLE `football_statistics` ADD `team_to_score_first_home` BOOLEAN NULL DEFAULT NULL AFTER `first_half_winner_away`;
ALTER TABLE `football_statistics` ADD `team_to_score_first_draw` BOOLEAN NULL DEFAULT NULL AFTER `team_to_score_first_home`;
ALTER TABLE `football_statistics` ADD `team_to_score_first_away` BOOLEAN NULL DEFAULT NULL AFTER `team_to_score_first_draw`;
ALTER TABLE `football_statistics` ADD `team_to_score_last_home` BOOLEAN NULL DEFAULT NULL AFTER `team_to_score_first_away`;
ALTER TABLE `football_statistics` ADD `team_to_score_last_draw` BOOLEAN NULL DEFAULT NULL AFTER `team_to_score_last_home`;
ALTER TABLE `football_statistics` ADD `team_to_score_last_away` BOOLEAN NULL DEFAULT NULL AFTER `team_to_score_last_draw`;
ALTER TABLE `football_statistics` ADD `total_home_over_15` BOOLEAN NULL DEFAULT NULL AFTER `team_to_score_last_away`;
ALTER TABLE `football_statistics` ADD `total_home_under_15` BOOLEAN NULL DEFAULT NULL AFTER `total_home_over_15`;
ALTER TABLE `football_statistics` ADD `total_home_over_25` BOOLEAN NULL DEFAULT NULL AFTER `total_home_under_15`;
ALTER TABLE `football_statistics` ADD `total_home_under_25` BOOLEAN NULL DEFAULT NULL AFTER `total_home_over_25`;
ALTER TABLE `football_statistics` ADD `total_home_over_35` BOOLEAN NULL DEFAULT NULL AFTER `total_home_under_25`;
ALTER TABLE `football_statistics` ADD `total_home_under_35` BOOLEAN NULL DEFAULT NULL AFTER `total_home_over_35`;
ALTER TABLE `football_statistics` ADD `total_home_over_45` BOOLEAN NULL DEFAULT NULL AFTER `total_home_under_35`;
ALTER TABLE `football_statistics` ADD `total_home_under_45` BOOLEAN NULL DEFAULT NULL AFTER `total_home_over_45`;
ALTER TABLE `football_statistics` ADD `total_home_over_55` BOOLEAN NULL DEFAULT NULL AFTER `total_home_under_45`;
ALTER TABLE `football_statistics` ADD `total_home_under_55` BOOLEAN NULL DEFAULT NULL AFTER `total_home_over_55`;
ALTER TABLE `football_statistics` ADD `total_home_over_65` BOOLEAN NULL DEFAULT NULL AFTER `total_home_under_55`;
ALTER TABLE `football_statistics` ADD `total_home_under_65` BOOLEAN NULL DEFAULT NULL AFTER `total_home_over_65`;
ALTER TABLE `football_statistics` ADD `total_away_over_15` BOOLEAN NULL DEFAULT NULL AFTER `total_home_under_65`;
ALTER TABLE `football_statistics` ADD `total_away_under_15` BOOLEAN NULL DEFAULT NULL AFTER `total_away_over_15`;
ALTER TABLE `football_statistics` ADD `total_away_over_25` BOOLEAN NULL DEFAULT NULL AFTER `total_away_under_15`;
ALTER TABLE `football_statistics` ADD `total_away_under_25` BOOLEAN NULL DEFAULT NULL AFTER `total_away_over_25`;
ALTER TABLE `football_statistics` ADD `total_away_over_35` BOOLEAN NULL DEFAULT NULL AFTER `total_away_under_25`;
ALTER TABLE `football_statistics` ADD `total_away_under_35` BOOLEAN NULL DEFAULT NULL AFTER `total_away_over_35`;
ALTER TABLE `football_statistics` ADD `total_away_over_45` BOOLEAN NULL DEFAULT NULL AFTER `total_away_under_35`;
ALTER TABLE `football_statistics` ADD `total_away_under_45` BOOLEAN NULL DEFAULT NULL AFTER `total_away_over_45`;
ALTER TABLE `football_statistics` ADD `total_away_over_55` BOOLEAN NULL DEFAULT NULL AFTER `total_away_under_45`;
ALTER TABLE `football_statistics` ADD `total_away_under_55` BOOLEAN NULL DEFAULT NULL AFTER `total_away_over_55`;
ALTER TABLE `football_statistics` ADD `total_away_over_65` BOOLEAN NULL DEFAULT NULL AFTER `total_away_under_55`;
ALTER TABLE `football_statistics` ADD `total_away_under_65` BOOLEAN NULL DEFAULT NULL AFTER `total_away_over_65`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_min_175` BOOLEAN NULL DEFAULT NULL AFTER `total_away_under_65`;

ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_min_175` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_min_175`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_min_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_min_175`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_min_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_min_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_min_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_min_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_min_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_min_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_min_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_min_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_min_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_min_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_min_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_min_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_min_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_min_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_min_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_min_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_min_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_min_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_min_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_min_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_min_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_min_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_min_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_0`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_0`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_025` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_025`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_05`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_075` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_075`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_1`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_125` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_125`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_15` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_home_plus_175` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_15`;
ALTER TABLE `football_statistics` ADD `asian_handicap_first_half_away_plus_175` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_home_plus_175`;
ALTER TABLE `football_statistics` ADD `double_chance__first_half_home_draw` BOOLEAN NULL DEFAULT NULL AFTER `asian_handicap_first_half_away_plus_175`;
ALTER TABLE `football_statistics` ADD `double_chance__first_half_home_away` BOOLEAN NULL DEFAULT NULL AFTER `double_chance__first_half_home_draw`;
ALTER TABLE `football_statistics` ADD `double_chance__first_half_draw_away` BOOLEAN NULL DEFAULT NULL AFTER `double_chance__first_half_home_away`;
ALTER TABLE `football_statistics` ADD `oddeven_odd` BOOLEAN NULL DEFAULT NULL AFTER `double_chance__first_half_draw_away`;
ALTER TABLE `football_statistics` ADD `oddeven_even` BOOLEAN NULL DEFAULT NULL AFTER `oddeven_odd`;
ALTER TABLE `football_statistics` ADD `results_both_teams_score_home_yes` BOOLEAN NULL DEFAULT NULL AFTER `oddeven_even`;
ALTER TABLE `football_statistics` ADD `results_both_teams_score_draw_yes` BOOLEAN NULL DEFAULT NULL AFTER `results_both_teams_score_home_yes`;
ALTER TABLE `football_statistics` ADD `results_both_teams_score_away_yes` BOOLEAN NULL DEFAULT NULL AFTER `results_both_teams_score_draw_yes`;
ALTER TABLE `football_statistics` ADD `results_both_teams_score_home_no` BOOLEAN NULL DEFAULT NULL AFTER `results_both_teams_score_away_yes`;
ALTER TABLE `football_statistics` ADD `results_both_teams_score_draw_no` BOOLEAN NULL DEFAULT NULL AFTER `results_both_teams_score_home_no`;
ALTER TABLE `football_statistics` ADD `results_both_teams_score_away_no` BOOLEAN NULL DEFAULT NULL AFTER `results_both_teams_score_draw_no`;
ALTER TABLE `football_statistics` ADD `result_total_goals_home_over_35` BOOLEAN NULL DEFAULT NULL AFTER `results_both_teams_score_away_no`;
ALTER TABLE `football_statistics` ADD `result_total_goals_draw_over_35` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_home_over_35`;
ALTER TABLE `football_statistics` ADD `result_total_goals_away_over_35` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_draw_over_35`;
ALTER TABLE `football_statistics` ADD `result_total_goals_home_under_35` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_away_over_35`;
ALTER TABLE `football_statistics` ADD `result_total_goals_draw_under_35` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_home_under_35`;
ALTER TABLE `football_statistics` ADD `result_total_goals_away_under_35` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_draw_under_35`;
ALTER TABLE `football_statistics` ADD `result_total_goals_home_over_25` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_away_under_35`;
ALTER TABLE `football_statistics` ADD `result_total_goals_draw_over_25` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_home_over_25`;
ALTER TABLE `football_statistics` ADD `result_total_goals_away_over_25` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_draw_over_25`;
ALTER TABLE `football_statistics` ADD `result_total_goals_home_under_25` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_away_over_25`;
ALTER TABLE `football_statistics` ADD `result_total_goals_draw_under_25` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_home_under_25`;
ALTER TABLE `football_statistics` ADD `result_total_goals_away_under_25` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_draw_under_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_05` BOOLEAN NULL DEFAULT NULL AFTER `result_total_goals_away_under_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_05` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_05`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_075` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_05`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_075` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_075`;

ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_10` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_075`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_10` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_10`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_125` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_10`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_125` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_125`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_15` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_125`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_15` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_15`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_175` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_15`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_175` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_175`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_20` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_175`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_20` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_20`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_225` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_20`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_225` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_225`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_25` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_225`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_25` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_275` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_25`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_275` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_275`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_30` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_275`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_30` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_30`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_325` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_30`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_325` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_325`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_35` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_325`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_35` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_35`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_over_375` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_35`;
ALTER TABLE `football_statistics` ADD `goals_overunder__second_half_under_375` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_over_375`;
ALTER TABLE `football_statistics` ADD `clean_sheet__home_yes` BOOLEAN NULL DEFAULT NULL AFTER `goals_overunder__second_half_under_375`;
ALTER TABLE `football_statistics` ADD `clean_sheet__home_no` BOOLEAN NULL DEFAULT NULL AFTER `clean_sheet__home_yes`;
ALTER TABLE `football_statistics` ADD `clean_sheet__away_yes` BOOLEAN NULL DEFAULT NULL AFTER `clean_sheet__home_no`;
ALTER TABLE `football_statistics` ADD `clean_sheet__away_no` BOOLEAN NULL DEFAULT NULL AFTER `clean_sheet__away_yes`;
ALTER TABLE `football_statistics` ADD `win_both_halves_home` BOOLEAN NULL DEFAULT NULL AFTER `clean_sheet__away_no`;
ALTER TABLE `football_statistics` ADD `win_both_halves_away` BOOLEAN NULL DEFAULT NULL AFTER `win_both_halves_home`;
ALTER TABLE `football_statistics` ADD `both_teams_score__first_half_yes` BOOLEAN NULL DEFAULT NULL AFTER `win_both_halves_away`;
ALTER TABLE `football_statistics` ADD `both_teams_score__first_half_no` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_score__first_half_yes`;
ALTER TABLE `football_statistics` ADD `both_teams_to_score__second_half_yes` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_score__first_half_no`;
ALTER TABLE `football_statistics` ADD `both_teams_to_score__second_half_no` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_to_score__second_half_yes`;
ALTER TABLE `football_statistics` ADD `win_to_nil_home` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_to_score__second_half_no`;
ALTER TABLE `football_statistics` ADD `win_to_nil_away` BOOLEAN NULL DEFAULT NULL AFTER `win_to_nil_home`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_0` BOOLEAN NULL DEFAULT NULL AFTER `win_to_nil_away`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_1` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_0`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_2` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_1`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_3` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_2`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_4` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_3`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_5` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_4`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_6` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_5`;
ALTER TABLE `football_statistics` ADD `exact_goals_number_more_7` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_6`;
ALTER TABLE `football_statistics` ADD `to_win_either_half_home` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number_more_7`;
ALTER TABLE `football_statistics` ADD `to_win_either_half_away` BOOLEAN NULL DEFAULT NULL AFTER `to_win_either_half_home`;
ALTER TABLE `football_statistics` ADD `home_team_exact_goals_number_0` BOOLEAN NULL DEFAULT NULL AFTER `to_win_either_half_away`;
ALTER TABLE `football_statistics` ADD `home_team_exact_goals_number_1` BOOLEAN NULL DEFAULT NULL AFTER `home_team_exact_goals_number_0`;
ALTER TABLE `football_statistics` ADD `home_team_exact_goals_number_2` BOOLEAN NULL DEFAULT NULL AFTER `home_team_exact_goals_number_1`;
ALTER TABLE `football_statistics` ADD `home_team_exact_goals_number_more_3` BOOLEAN NULL DEFAULT NULL AFTER `home_team_exact_goals_number_2`;
ALTER TABLE `football_statistics` ADD `away_team_exact_goals_number_0` BOOLEAN NULL DEFAULT NULL AFTER `home_team_exact_goals_number_more_3`;
ALTER TABLE `football_statistics` ADD `away_team_exact_goals_number_1` BOOLEAN NULL DEFAULT NULL AFTER `away_team_exact_goals_number_0`;
ALTER TABLE `football_statistics` ADD `away_team_exact_goals_number_2` BOOLEAN NULL DEFAULT NULL AFTER `away_team_exact_goals_number_1`;
ALTER TABLE `football_statistics` ADD `away_team_exact_goals_number_more_3` BOOLEAN NULL DEFAULT NULL AFTER `away_team_exact_goals_number_2`;
ALTER TABLE `football_statistics` ADD `second_half_exact_goals_number_0` BOOLEAN NULL DEFAULT NULL AFTER `away_team_exact_goals_number_more_3`;
ALTER TABLE `football_statistics` ADD `second_half_exact_goals_number_1` BOOLEAN NULL DEFAULT NULL AFTER `second_half_exact_goals_number_0`;
ALTER TABLE `football_statistics` ADD `second_half_exact_goals_number_2` BOOLEAN NULL DEFAULT NULL AFTER `second_half_exact_goals_number_1`;
ALTER TABLE `football_statistics` ADD `second_half_exact_goals_number_3` BOOLEAN NULL DEFAULT NULL AFTER `second_half_exact_goals_number_2`;
ALTER TABLE `football_statistics` ADD `second_half_exact_goals_number_4` BOOLEAN NULL DEFAULT NULL AFTER `second_half_exact_goals_number_3`;
ALTER TABLE `football_statistics` ADD `second_half_exact_goals_number_more_5` BOOLEAN NULL DEFAULT NULL AFTER `second_half_exact_goals_number_4`;

ALTER TABLE `football_statistics` ADD `corners_over_under_over_700` BOOLEAN NULL DEFAULT NULL AFTER `second_half_exact_goals_number_more_5`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_700` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_700`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_725` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_700`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_725` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_725`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_750` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_725`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_750` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_750`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_775` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_750`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_775` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_775`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_800` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_775`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_800` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_800`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_825` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_800`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_825` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_825`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_850` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_825`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_850` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_850`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_875` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_850`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_875` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_875`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_900` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_875`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_900` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_900`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_925` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_900`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_925` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_925`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_950` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_925`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_950` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_950`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_975` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_950`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_975` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_975`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1000` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_975`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1000` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1000`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1025` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1000`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1025` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1025`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1050` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1025`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1050` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1050`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1075` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1050`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1075` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1075`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1100` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1075`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1100` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1100`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1125` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1100`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1125` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1125`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1150` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1125`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1150` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1150`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1175` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1150`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1175` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1175`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1200` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1175`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1200` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1200`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1225` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1200`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1225` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1225`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1250` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1225`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1250` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1250`;
ALTER TABLE `football_statistics` ADD `corners_over_under_over_1275` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1250`;
ALTER TABLE `football_statistics` ADD `corners_over_under_under_1275` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_over_1275`;
ALTER TABLE `football_statistics` ADD `exact_goals_number__first_half_0` BOOLEAN NULL DEFAULT NULL AFTER `corners_over_under_under_1275`;
ALTER TABLE `football_statistics` ADD `exact_goals_number__first_half_1` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number__first_half_0`;
ALTER TABLE `football_statistics` ADD `exact_goals_number__first_half_2` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number__first_half_1`;
ALTER TABLE `football_statistics` ADD `exact_goals_number__first_half_3` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number__first_half_2`;
ALTER TABLE `football_statistics` ADD `exact_goals_number__first_half_4` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number__first_half_3`;
ALTER TABLE `football_statistics` ADD `exact_goals_number__first_half_more_5` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number__first_half_4`;
ALTER TABLE `football_statistics` ADD `to_score_in_both_halves_by_teams_home` BOOLEAN NULL DEFAULT NULL AFTER `exact_goals_number__first_half_more_5`;
ALTER TABLE `football_statistics` ADD `to_score_in_both_halves_by_teams_away` BOOLEAN NULL DEFAULT NULL AFTER `to_score_in_both_halves_by_teams_home`;
ALTER TABLE `football_statistics` ADD `total_goals_both_teams_to_score_over_yes_25` BOOLEAN NULL DEFAULT NULL AFTER `to_score_in_both_halves_by_teams_away`;
ALTER TABLE `football_statistics` ADD `total_goals_both_teams_to_score_over_no_25` BOOLEAN NULL DEFAULT NULL AFTER `total_goals_both_teams_to_score_over_yes_25`;
ALTER TABLE `football_statistics` ADD `total_goals_both_teams_to_score_under_yes_25` BOOLEAN NULL DEFAULT NULL AFTER `total_goals_both_teams_to_score_over_no_25`;
ALTER TABLE `football_statistics` ADD `total_goals_both_teams_to_score_under_no_25` BOOLEAN NULL DEFAULT NULL AFTER `total_goals_both_teams_to_score_under_yes_25`;
ALTER TABLE `football_statistics` ADD `halftime_result_both_teams_score_home_yes` BOOLEAN NULL DEFAULT NULL AFTER `total_goals_both_teams_to_score_under_no_25`;

ALTER TABLE `football_statistics` ADD `halftime_result_both_teams_score_draw_yes` BOOLEAN NULL DEFAULT NULL AFTER `halftime_result_both_teams_score_home_yes`;
ALTER TABLE `football_statistics` ADD `halftime_result_both_teams_score_away_yes` BOOLEAN NULL DEFAULT NULL AFTER `halftime_result_both_teams_score_draw_yes`;
ALTER TABLE `football_statistics` ADD `halftime_result_both_teams_score_home_no` BOOLEAN NULL DEFAULT NULL AFTER `halftime_result_both_teams_score_away_yes`;
ALTER TABLE `football_statistics` ADD `halftime_result_both_teams_score_draw_no` BOOLEAN NULL DEFAULT NULL AFTER `halftime_result_both_teams_score_home_no`;
ALTER TABLE `football_statistics` ADD `halftime_result_both_teams_score_away_no` BOOLEAN NULL DEFAULT NULL AFTER `halftime_result_both_teams_score_draw_no`;
ALTER TABLE `football_statistics` ADD `corners_winner_home` BOOLEAN NULL DEFAULT NULL AFTER `halftime_result_both_teams_score_away_no`;
ALTER TABLE `football_statistics` ADD `corners_winner_draw` BOOLEAN NULL DEFAULT NULL AFTER `corners_winner_home`;
ALTER TABLE `football_statistics` ADD `corners_winner_away` BOOLEAN NULL DEFAULT NULL AFTER `corners_winner_draw`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_65` BOOLEAN NULL DEFAULT NULL AFTER `corners_winner_away`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_65` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_65`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_6` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_65`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_6` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_6`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_55` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_6`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_55` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_55`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_5` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_55`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_5` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_5`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_45` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_5`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_45` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_45`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_4` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_45`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_4` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_4`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_35` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_4`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_35` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_35`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_3` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_35`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_3` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_3`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_25` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_3`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_25` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_25`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_2` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_25`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_2` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_2`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_15` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_2`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_15` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_15`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_1` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_15`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_min_05` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_1`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_1` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_min_05`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_min_05` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_1`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_min_05`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_0`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_0`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_05`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_05`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_1`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_15` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_1`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_15` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_15`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_2` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_15`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_2` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_2`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_25` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_2`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_25` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_25`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_3` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_25`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_3` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_3`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_35` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_3`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_35` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_35`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_4` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_35`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_4` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_4`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_45` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_4`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_45` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_45`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_5` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_45`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_5` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_5`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_55` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_5`;

ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_55` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_55`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_6` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_55`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_6` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_6`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_home_plus_65` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_6`;
ALTER TABLE `football_statistics` ADD `corners_asian_handicap_away_plus_65` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_home_plus_65`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_over_25` BOOLEAN NULL DEFAULT NULL AFTER `corners_asian_handicap_away_plus_65`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_under_25` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_over_25`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_over_35` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_under_25`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_under_35` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_over_35`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_over_45` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_under_35`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_under_45` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_over_45`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_over_55` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_under_45`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_under_55` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_over_55`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_over_65` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_under_55`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_under_65` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_over_65`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_over_75` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_under_65`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_under_75` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_over_75`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_over_85` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_under_75`;
ALTER TABLE `football_statistics` ADD `home_corners_overunder_under_85` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_over_85`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_over_25` BOOLEAN NULL DEFAULT NULL AFTER `home_corners_overunder_under_85`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_under_25` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_over_25`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_over_35` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_under_25`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_under_35` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_over_35`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_over_45` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_under_35`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_under_45` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_over_45`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_over_55` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_under_45`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_under_55` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_over_55`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_over_65` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_under_55`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_under_65` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_over_65`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_over_75` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_under_65`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_under_75` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_over_75`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_over_85` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_under_75`;
ALTER TABLE `football_statistics` ADD `away_corners_overunder_under_85` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_over_85`;
ALTER TABLE `football_statistics` ADD `both_teams_to_score_1st_half__2nd_half_yes_yes` BOOLEAN NULL DEFAULT NULL AFTER `away_corners_overunder_under_85`;
ALTER TABLE `football_statistics` ADD `both_teams_to_score_1st_half__2nd_half_yes_no` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_to_score_1st_half__2nd_half_yes_yes`;
ALTER TABLE `football_statistics` ADD `both_teams_to_score_1st_half__2nd_half_no_yes` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_to_score_1st_half__2nd_half_yes_no`;
ALTER TABLE `football_statistics` ADD `both_teams_to_score_1st_half__2nd_half_no_no` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_to_score_1st_half__2nd_half_no_yes`;
ALTER TABLE `football_statistics` ADD `10_overunder_over_05` BOOLEAN NULL DEFAULT NULL AFTER `both_teams_to_score_1st_half__2nd_half_no_no`;
ALTER TABLE `football_statistics` ADD `10_overunder_under_05` BOOLEAN NULL DEFAULT NULL AFTER `10_overunder_over_05`;
ALTER TABLE `football_statistics` ADD `last_corner_home` BOOLEAN NULL DEFAULT NULL AFTER `10_overunder_under_05`;
ALTER TABLE `football_statistics` ADD `last_corner_away` BOOLEAN NULL DEFAULT NULL AFTER `last_corner_home`;
ALTER TABLE `football_statistics` ADD `first_corner_home` BOOLEAN NULL DEFAULT NULL AFTER `last_corner_away`;
ALTER TABLE `football_statistics` ADD `first_corner_away` BOOLEAN NULL DEFAULT NULL AFTER `first_corner_home`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_home_min_2` BOOLEAN NULL DEFAULT NULL AFTER `first_corner_away`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_draw_min_2` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_home_min_2`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_away_min_2` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_draw_min_2`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_home_min_1` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_away_min_2`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_draw_min_1` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_home_min_1`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_away_min_1` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_draw_min_1`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_home_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_away_min_1`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_draw_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_home_plus_0`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_away_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_draw_plus_0`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_home_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_away_plus_0`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_draw_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_home_plus_1`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_away_plus_1` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_draw_plus_1`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_home_plus_2` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_away_plus_1`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_draw_plus_2` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_home_plus_2`;
ALTER TABLE `football_statistics` ADD `cards_european_handicap_away_plus_2` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_draw_plus_2`;
ALTER TABLE `football_statistics` ADD `cards_overunder_over_25` BOOLEAN NULL DEFAULT NULL AFTER `cards_european_handicap_away_plus_2`;

ALTER TABLE `football_statistics` ADD `cards_overunder_under_25` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_over_25`;
ALTER TABLE `football_statistics` ADD `cards_overunder_over_35` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_under_25`;
ALTER TABLE `football_statistics` ADD `cards_overunder_under_35` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_over_35`;
ALTER TABLE `football_statistics` ADD `cards_overunder_over_45` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_under_35`;
ALTER TABLE `football_statistics` ADD `cards_overunder_under_45` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_over_45`;
ALTER TABLE `football_statistics` ADD `cards_overunder_over_55` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_under_45`;
ALTER TABLE `football_statistics` ADD `cards_overunder_under_55` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_over_55`;
ALTER TABLE `football_statistics` ADD `cards_overunder_over_65` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_under_55`;
ALTER TABLE `football_statistics` ADD `cards_overunder_under_65` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_over_65`;
ALTER TABLE `football_statistics` ADD `cards_overunder_over_75` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_under_65`;
ALTER TABLE `football_statistics` ADD `cards_overunder_under_75` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_over_75`;
ALTER TABLE `football_statistics` ADD `cards_asian_handicap_home_min_05` BOOLEAN NULL DEFAULT NULL AFTER `cards_overunder_under_75`;
ALTER TABLE `football_statistics` ADD `cards_asian_handicap_away_min_05` BOOLEAN NULL DEFAULT NULL AFTER `cards_asian_handicap_home_min_05`;
ALTER TABLE `football_statistics` ADD `cards_asian_handicap_home_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `cards_asian_handicap_away_min_05`;
ALTER TABLE `football_statistics` ADD `cards_asian_handicap_away_plus_0` BOOLEAN NULL DEFAULT NULL AFTER `cards_asian_handicap_home_plus_0`;
ALTER TABLE `football_statistics` ADD `cards_asian_handicap_home_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `cards_asian_handicap_away_plus_0`;
ALTER TABLE `football_statistics` ADD `cards_asian_handicap_away_plus_05` BOOLEAN NULL DEFAULT NULL AFTER `cards_asian_handicap_home_plus_05`;
ALTER TABLE `football_statistics` ADD `home_team_total_cards_over_15` BOOLEAN NULL DEFAULT NULL AFTER `cards_asian_handicap_away_plus_05`;
ALTER TABLE `football_statistics` ADD `home_team_total_cards_under_15` BOOLEAN NULL DEFAULT NULL AFTER `home_team_total_cards_over_15`;
ALTER TABLE `football_statistics` ADD `home_team_total_cards_over_25` BOOLEAN NULL DEFAULT NULL AFTER `home_team_total_cards_under_15`;
ALTER TABLE `football_statistics` ADD `home_team_total_cards_under_25` BOOLEAN NULL DEFAULT NULL AFTER `home_team_total_cards_over_25`;
ALTER TABLE `football_statistics` ADD `home_team_total_cards_over_35` BOOLEAN NULL DEFAULT NULL AFTER `home_team_total_cards_under_25`;
ALTER TABLE `football_statistics` ADD `home_team_total_cards_under_35` BOOLEAN NULL DEFAULT NULL AFTER `home_team_total_cards_over_35`;
ALTER TABLE `football_statistics` ADD `away_team_total_cards_over_15` BOOLEAN NULL DEFAULT NULL AFTER `home_team_total_cards_under_35`;
ALTER TABLE `football_statistics` ADD `away_team_total_cards_under_15` BOOLEAN NULL DEFAULT NULL AFTER `away_team_total_cards_over_15`;
ALTER TABLE `football_statistics` ADD `away_team_total_cards_over_25` BOOLEAN NULL DEFAULT NULL AFTER `away_team_total_cards_under_15`;
ALTER TABLE `football_statistics` ADD `away_team_total_cards_under_25` BOOLEAN NULL DEFAULT NULL AFTER `away_team_total_cards_over_25`;
ALTER TABLE `football_statistics` ADD `away_team_total_cards_over_35` BOOLEAN NULL DEFAULT NULL AFTER `away_team_total_cards_under_25`;
ALTER TABLE `football_statistics` ADD `away_team_total_cards_under_35` BOOLEAN NULL DEFAULT NULL AFTER `away_team_total_cards_over_35`;
ALTER TABLE `football_statistics` ADD `rcard_yes` BOOLEAN NULL DEFAULT NULL AFTER `away_team_total_cards_under_35`;
ALTER TABLE `football_statistics` ADD `rcard_no` BOOLEAN NULL DEFAULT NULL AFTER `rcard_yes`;
ALTER TABLE `football_statistics` ADD `total_goals_under_2` BOOLEAN NULL DEFAULT NULL AFTER `rcard_no`;
ALTER TABLE `football_statistics` ADD `total_goals_2_or_3` BOOLEAN NULL DEFAULT NULL AFTER `total_goals_under_2`;
ALTER TABLE `football_statistics` ADD `total_goals_over_3` BOOLEAN NULL DEFAULT NULL AFTER `total_goals_2_or_3`;
ALTER TABLE `football_statistics` ADD `first_goal_method_shot` BOOLEAN NULL DEFAULT NULL AFTER `total_goals_over_3`;
ALTER TABLE `football_statistics` ADD `first_goal_method_header` BOOLEAN NULL DEFAULT NULL AFTER `first_goal_method_shot`;
ALTER TABLE `football_statistics` ADD `first_goal_method_penalty` BOOLEAN NULL DEFAULT NULL AFTER `first_goal_method_header`;
ALTER TABLE `football_statistics` ADD `first_goal_method_freekick` BOOLEAN NULL DEFAULT NULL AFTER `first_goal_method_penalty`;
ALTER TABLE `football_statistics` ADD `first_goal_method_owngoal` BOOLEAN NULL DEFAULT NULL AFTER `first_goal_method_freekick`;
ALTER TABLE `football_statistics` ADD `first_goal_method_draw` BOOLEAN NULL DEFAULT NULL AFTER `first_goal_method_owngoal`;
ALTER TABLE `football_statistics` ADD `to_score_a_penalty_home` BOOLEAN NULL DEFAULT NULL AFTER `first_goal_method_draw`;
ALTER TABLE `football_statistics` ADD `to_score_a_penalty_away` BOOLEAN NULL DEFAULT NULL AFTER `to_score_a_penalty_home`;
ALTER TABLE `football_statistics` ADD `to_miss_a_penalty_home` BOOLEAN NULL DEFAULT NULL AFTER `to_score_a_penalty_away`;
ALTER TABLE `football_statistics` ADD `to_miss_a_penalty_away` BOOLEAN NULL DEFAULT NULL AFTER `to_miss_a_penalty_home`;